### ISSUE TITLE
Variables in config

### ISSUE THREAD

**Issue by TheCynicalLiger** [RasmusLindroth/i3keys#18]
hey mate i dont know if you are still working on this but any way you could make it so that things like below will work. because i myself do you use bindsym in the config itself my keys dont seem to show up at all if you want an example of my config [here it is](https://raw.githubusercontent.com/TheCynicalTeam/DotFiles/master/.config/i3/config)

```
set $super      Mod4
set $super_b    bindsym Mod4
set $alt        Mod1
set $alt_b      bindsym Mod1
set $control    Control
set $control_b  bindsym Control
set $shift      Shift
set $shift_b    bindsym Shift
set $exe        exec --no-startup-id
set $exe_always exec_always --no-startup-id
```

**Comment by RasmusLindroth** [comment]
Thank you for the bug report and yes, I'm still working on this. I think I should be able to fix this quite easily, I will look at it more closely in the near future :)

**Comment by TheCynicalLiger** [comment]
maybe have 1 command that will read `regex = r"\s*set (\$\S+)\s+(.+)"` then replace $super with Mod4 im not too good with go so not to sure on how to do this myself... if you could maybe upload a build that works with my config that would be awesome :)

**Comment by RasmusLindroth** [comment]
I think I managed to solve it :)

**Comment by TheCynicalLiger** [comment]
yup all sorted got it working :) https://thecynicalteam.github.io/i3_keybinds/keybinds.html

**Comment by TheCynicalLiger** [comment]
oops just took another look and seems like the CONTROL key doesnt highlight green like the rest do :)
