### ISSUE TITLE
"i3keys web" ==> Mod4+Alt keyboard does not have the Alt keys in green

### ISSUE THREAD

**Issue by scott092707** [RasmusLindroth/i3keys#26]
For Debian Testing + sway 1.5.1-2 + Firefox ESR 78.13.0esr (64-bit).

The Mod4+Shift keyboard has both the Super_ and  Shift_  modifier keys colored green.
The Mod4+Alt keyboard has only the Super_ keys colored green - the Alt_ keys are white.

I have no  Mod4_Ctrl  keybindings, so I suppose that is why there is no Mod4+Ctrl keyboard.
(Likewise with  Mod4+Shift+Alt  or  Mod4+Ctrl+Alt  or  Mod4+Shift+Alt+Ctrl  ...  ?)

Therefore, I do not know if there is also a problem with the other modifier combinations...
![NoGreenAlt](https://user-images.githubusercontent.com/7544310/138575689-4732ab7b-b4f4-4b13-b5e7-3fadea8103f0.png)

**Comment by RasmusLindroth** [comment]
Fixed thanks to @elder-n00b
